USE master;

DROP DATABASE IF EXISTS Unternehm ;

CREATE DATABASE Unternehm;
GO
USE Unternehm;
GO

CREATE TABLE Abteilung (
  PK_Abt_nr INTEGER IDENTITY PRIMARY KEY NOT NULL,
  Name VARCHAR(64) NOT NULL,
  Anzahl_Angestellte INTEGER,
  Email VARCHAR(128) NOT NULL,
  Telefon VARCHAR(64) NOT NULL,
  active BIT DEFAULT 'TRUE'
);

CREATE TABLE Niederlassung (
  PK_FirmaID INTEGER IDENTITY PRIMARY KEY NOT NULL,
  Ort VARCHAR(64) NOT NULL,
  Telefon VARCHAR(64) NOT NULL,
  Email VARCHAR(64) NOT NULL,
  active BIT DEFAULT 'TRUE'
);

CREATE TABLE Projekt (
  PK_Proj_nr INTEGER IDENTITY PRIMARY KEY NOT NULL,
  Name VARCHAR(128) NOT NULL,
  Start_Date DATETIME2 NOT NULL,
  End_Date DATETIME2,
  active BIT DEFAULT 'TRUE'
);

CREATE TABLE Kunde (
  PK_KundID INTEGER IDENTITY PRIMARY KEY NOT NULL,
  Vorname VARCHAR(64) NOT NULL,
  Nachname VARCHAR(64) NOT NULL,
  Sex VARCHAR(1) CHECK (Sex IN ('F','M')),
  Adresse VARCHAR(128),
  PLZ_Stadt VARCHAR(64) NOT NULL,
  Telefon VARCHAR(64) NOT NULL,
  Email VARCHAR(128) NOT NULL,
  active BIT DEFAULT 'TRUE'
);

CREATE TABLE Angestellte (
  PK_AngID INTEGER IDENTITY PRIMARY KEY NOT NULL,
  Sex VARCHAR(1) CHECK (Sex IN ('F','M')),
  Vorname VARCHAR(64) NOT NULL,
  Nachname VARCHAR(64) NOT NULL,
  Email VARCHAR(128),
  Gehalt INTEGER NOT NULL,
  FK_FirmaID INTEGER REFERENCES Niederlassung(PK_FirmaID),
  FK_Abt_nr INTEGER REFERENCES Abteilung(PK_Abt_nr),
  active BIT DEFAULT 'TRUE'
);

CREATE TABLE Bestellung (
  BessID INTEGER IDENTITY PRIMARY KEY NOT NULL,
  FK_Proj INTEGER NOT NULL REFERENCES Projekt(PK_Proj_nr),
  FK_Kunde INTEGER NOT NULL REFERENCES Kunde(PK_KundID),
  Datum DATETIME2 NOT NULL,
  Preis INTEGER NOT NULL
);

CREATE TABLE Pro_Ang(
  FK_AngID INTEGER NOT NULL REFERENCES Angestellte(PK_AngID) ,
  FK_Proj_nr INTEGER NOT NULL REFERENCES Projekt(PK_Proj_nr)
);
